# Generated by Django 3.0.5 on 2020-04-25 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('payload', models.BinaryField(max_length=50)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.Module')),
            ],
        ),
    ]
