# Generated by Django 3.0.5 on 2020-04-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('guid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('guid', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('timestamp', models.IntegerField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.Hub')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubs.Module')),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='modules',
            field=models.ManyToManyField(to='hubs.Module'),
        ),
    ]
